name: CI
on:
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/aafiqbinkhayer-Toshiro/kernel_xiaomi_spes
          kernel-branch: spes-r-oss
          config: vendor/spes-perf_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 11
